switch:
- platform: command_line
  switches:
    lounge_tv_bed:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/bed-cam.strm" }}}' lounge-kodi.rb.kohi.uk:8080/jsonrpc
    lounge_tv_bedroom:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/bedroom-cam.strm" }}}' lounge-kodi.rb.kohi.uk:8080/jsonrpc
    lounge_tv_cot:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/cot-cam.strm" }}}' lounge-kodi.rb.kohi.uk:8080/jsonrpc
    kitchen_tv_bed:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/bed-cam.strm" }}}' kitchen-kodi.rb.kohi.uk:8080/jsonrpc
    kitchen_tv_bedroom:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/bedroom-cam.strm" }}}' kitchen-kodi.rb.kohi.uk:8080/jsonrpc
    kitchen_tv_cot:
      command_on: >
        curl --header "Content-Type: application/json" --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "nfs://downloads.rb.kohi.uk/mnt/videos/tv/Cams/cot-cam.strm" }}}' kitchen-kodi.rb.kohi.uk:8080/jsonrpc 
