switch:
- platform: flux
  lights:
    - light.landing
    - light.hallway
  name: Fluxer
  start_time: "7:00"
  stop_time: "23:00"
  start_colortemp: 3000
  sunset_colortemp: 2500
  stop_colortemp: 1600
  disable_brightness_adjust: False
  mode: mired