sensor:
- platform: miflora
  mac: "C4:7C:8D:64:42:36"
  name: Lucky Plant
  force_update: false
  median: 3
  monitored_conditions:
    - temperature
    - light
    - moisture
    - battery
    - conductivity
#- platform: miflora
#  mac: 'C4:7C:8D:63:78:A4'
#  name: Unused
#  force_update: false
#  median: 3
#  monitored_conditions:
#    - temperature
#    - light
#    - moisture
#    - battery
#    - conductivity