binary_sensor:
  - platform: template
    sensors:
      watching_tv:
        friendly_name: Watching Tv
        value_template: "{{ 
          is_state('media_player.lounge_kodi', 'playing')
          or is_state('media_player.lounge', 'playing')
        }}"
