switch:
  - platform: command_line
    switches:
      lounge_tv:
        friendly_name: Lounge Tv
        command_on: >
          curl --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"activate"}},"id":1}' http://lounge-kodi.rb.kohi.uk:8080/jsonrpc?request=
        command_off: >
          curl --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"standby"}},"id":1}' http://lounge-kodi.rb.kohi.uk:8080/jsonrpc?request=

binary_sensor:
  - platform: template
    sensors:
      watching_tv:
        friendly_name: Watching Tv
        value_template: "{{ 
          is_state('media_player.lounge_kodi', 'playing')
          or is_state('media_player.lounge', 'playing')
        }}"