binary_sensor:
  - platform: template
    sensors:
      vacuuming:
        friendly_name: Vacuuming
        value_template: "{{ 
          is_state('vacuum.downstairs_robocop', 'cleaning')
          or is_state('vacuum.downstairs_robocops', 'returning')
          or is_state('vacuum.upstairs_robocop', 'cleaning')
          or is_state('vacuum.upstairs_robocop', 'returning')
        }}"
        delay_off:
          minutes: 2
